# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with security scans

on:
  workflow_dispatch:
  
  push:
    branches: [ "KrznaricPaula_SC" ]
  pull_request:
    branches: [ "KrznaricPaula_SC" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk scan
        run: snyk test || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Start podcast app
        run: |
          nohup mvn spring-boot:run > app.log 2>&1 &
          sleep 30

      - name: Check app
        run: curl --fail http://localhost:8080

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://172.17.0.1:8080'

   

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
